/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  theme: {
    extend: {
      fontFamily: {
        heading: ['Nunito', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        body: ['"DM Sans"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
        primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
        secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
        cream: '#FFF8EF',
        navy: {
          DEFAULT: '#0E2235',
          900: '#0E2235',
          800: '#17304a',
          700: '#2b4a64',
          600: '#46647e',
          500: '#5d7991',
          400: '#8aa1b4',
          300: '#b9c7d3',
          200: '#dbe3ea',
        },
        amber: {
          DEFAULT: '#F5A623',
          400: '#FFC15E',
          500: '#F5A623',
          600: '#FF8A3D',
        },
        azure: {
          DEFAULT: '#3DA5E0',
          400: '#6FBEEB',
          500: '#3DA5E0',
          600: '#2B8FC9',
        },
        leaf: {
          DEFAULT: '#3FB06A',
          400: '#6CC790',
          500: '#3FB06A',
          600: '#329257',
        },
      },
      boxShadow: {
        soft: '0 8px 30px rgba(14,34,53,0.06)',
        lift: '0 20px 45px rgba(14,34,53,0.10)',
        amber: '0 10px 24px rgba(245,166,35,0.35)',
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        floaty: { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-8px)' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        floaty: 'floaty 5s ease-in-out infinite',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
